services:
  haproxy:
    image: haproxy:3.2.0-alpine
    container_name: haproxy
    restart: unless-stopped

    ports:
      - 80:80
      - 443:443

    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./scripts:/usr/local/bin/haproxy-scripts:ro
      - "${HAPROXY_CERTS_DIR:?Укажите HAPROXY_CERTS_DIR в .env}:/etc/haproxy/certs:ro"

    group_add:
      - "${EXPORT_GID:?Укажите EXPORT_GID в .env}"

    entrypoint: ["/bin/sh", "/usr/local/bin/haproxy-scripts/entrypoint.sh"]

    networks:
      - haproxy

networks:
  haproxy:
    name: haproxy
